# Generated by Django 4.1.3 on 2022-11-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='x-rays')),
                ('prediction', models.CharField(blank=True, choices=[(0, 'Normal'), (1, 'Pneumonia')], max_length=200, null=True)),
            ],
        ),
    ]
